export const INJURY_UPDATE_REQUEST = "INJURY_UPDATE_REQUEST";
export const INJURY_UPDATE_FAIL = "INJURY_UPDATE_FAIL";
export const INJURY_UPDATE_SUCCESS = "INJURY_UPDATE_SUCCESS";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const UPDATE_GENDER = "UPDATE_GENDER";
export const UPDATE_AGE = "UPDATE_AGE";

export const ACCIDENT_STATE = "ACCIDENT_STATE";
export const ACCIDENT_DATE = "ACCIDENT_DATE";

export const DRIVER_OR_PASSENGER = "DRIVER_OR_PASSENGER";

export const CALCULATE = "CALCULATE";
